name: first-workflow
on: [push]

job:
  sell-cmd-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello
        run: echo "Hello World"
      - name: multiple line command
        run: |
          node -v
          npm -v